Update to API 4.6
elbekD/kt-telegram-bot pull request #19
Opened 2020-01-30 17:12 UTC by dragneelfps

Related to Issue https://github.com/elbekD/kt-telegram-bot/issues/18

2020-02-02 21:18 UTC, elbekD requested changes

2020-02-02 21:18 UTC, elbekD commented on library/src/main/kotlin/com/elbekD/bot/TelegramBot.kt
> +import com.elbekD.bot.types.*
do not use * imports

2020-02-02 21:18 UTC, elbekD commented on library/src/main/kotlin/com/elbekD/bot/TelegramBot.kt
>              client.sendPoll(chatId, question, options, disableNotification, replyTo, markup)
did u miss adding new params to client.sendPoll method?

2020-02-02 21:18 UTC, elbekD commented on library/src/main/kotlin/com/elbekD/bot/http/TelegramApi.kt
> +import com.elbekD.bot.types.*
imports

2020-02-02 21:18 UTC, elbekD commented on library/src/main/kotlin/com/elbekD/bot/http/TelegramClient.kt
> +import com.elbekD.bot.types.*
imports

2020-02-02 21:18 UTC, elbekD commented on library/src/main/kotlin/com/elbekD/bot/http/TelegramClient.kt
> +import okhttp3.*
imports

2020-02-02 21:18 UTC, elbekD commented on library/src/test/kotlin/com/elbekD/bot/TelegramBotTest.kt
> +import org.junit.Assert.*
imports

2020-02-09 11:57 UTC, elbekD commented
Hi @dragneelfps! Are you going to solve comments in a few days?

2020-02-11 17:55 UTC, dragneelfps commented
@elbekD you can go ahead and add commits to resolve the comments.

2020-02-16 09:43 UTC, merged